name: Create Release PR
on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

jobs:
  OnPullRequest:
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World!"
    - name: My Secret
      run: echo ${{ secrets.MY_SECRET }} > my_secret.txt
    - name: Read Secret
      run: cat my_secret.txt
