name: Release Images
on:
  pull_request_review:
    types: [submitted]

jobs:
  release-test:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:') && github.event.review.state == 'approved'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: cat release.json
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "TRACE"  # or "DEBUG"
          MERGE_LABELS: release
          MERGE_METHOD: squash
